"""add year

Revision ID: 27d2620ffb1c
Revises: 5cbe99cb4266
Create Date: 2024-05-26 09:19:35.826924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27d2620ffb1c'
down_revision: Union[str, None] = '5cbe99cb4266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'year')
    # ### end Alembic commands ###
